"""add user_id to drivers

Revision ID: 0d2159079d56
Revises: a50ee02a4d15
Create Date: 2026-07-31 22:44:14.562717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2159079d56'
down_revision: Union[str, Sequence[str], None] = 'a50ee02a4d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        'drivers',
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=True
        )
    )

    op.create_foreign_key(
        'fk_driver_user',
        'drivers',
        'users',
        ['user_id'],
        ['id']
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'user_id')
    # ### end Alembic commands ###
