"""add vehicle_id to drivers

Revision ID: 1702e3334605
Revises: f1283af35a85
Create Date: 2026-08-03 10:47:28.028873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1702e3334605'
down_revision: Union[str, Sequence[str], None] = 'f1283af35a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'vehicle_id')
    # ### end Alembic commands ###
