"""create delivery assignments table

Revision ID: 69a23c2a5238
Revises: c990935323a4
Create Date: 2026-08-01 13:37:40.580039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69a23c2a5238'
down_revision: Union[str, Sequence[str], None] = 'c990935323a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_distance', sa.Float(), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_assignments_id'), 'delivery_assignments', ['id'], unique=False)
    op.alter_column('deliveries', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('deliveries', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='deliverypriority'),
               nullable=False)
    op.alter_column('deliveries', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('deliveries', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='deliverypriority'),
               nullable=True)
    op.alter_column('deliveries', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_delivery_assignments_id'), table_name='delivery_assignments')
    op.drop_table('delivery_assignments')
    # ### end Alembic commands ###
