"""add delivery status history

Revision ID: c244ecd279ec
Revises: 6967800fd2ab
Create Date: 2026-08-01 14:34:50.229009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c244ecd279ec'
down_revision: Union[str, Sequence[str], None] = '6967800fd2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_status_history_id'), 'delivery_status_history', ['id'], unique=False)
    op.alter_column('tracking_history', 'delivery_status',
               existing_type=postgresql.ENUM('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='deliverystatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracking_history', 'delivery_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='deliverystatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_delivery_status_history_id'), table_name='delivery_status_history')
    op.drop_table('delivery_status_history')
    # ### end Alembic commands ###
