"""add speed and status to tracking

Revision ID: d97e7933550a
Revises: 69a23c2a5238
Create Date: 2026-08-01 13:46:44.387217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97e7933550a'
down_revision: Union[str, Sequence[str], None] = '69a23c2a5238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # add speed column with default value
    op.add_column(
        'tracking_history',
        sa.Column(
            'speed',
            sa.Float(),
            nullable=False,
            server_default="0"
        )
    )

    # add delivery status column
    op.add_column(
        'tracking_history',
        sa.Column(
            'status',
            sa.String(length=50),
            nullable=False,
            server_default="PENDING"
        )
    )


def downgrade() -> None:

    op.drop_column(
        'tracking_history',
        'status'
    )

    op.drop_column(
        'tracking_history',
        'speed'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_history', 'delivery_status')
    op.drop_column('tracking_history', 'speed')
    # ### end Alembic commands ###
