"""rename status to delivery_status in tracking

Revision ID: fc7d80aea2dc
Revises: d97e7933550a
Create Date: 2026-08-01 13:56:43.955027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7d80aea2dc'
down_revision: Union[str, Sequence[str], None] = 'd97e7933550a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        'tracking_history',
        sa.Column(
            'delivery_status',
            sa.Enum(
                'PENDING',
                'ASSIGNED',
                'IN_TRANSIT',
                'DELIVERED',
                'CANCELLED',
                name='deliverystatus'
            ),
            nullable=True
        )
    )


    op.execute(
        """
        UPDATE tracking_history
        SET delivery_status = 'PENDING'
        WHERE delivery_status IS NULL
        """
    )


    op.alter_column(
        'tracking_history',
        'delivery_status',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_history', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('tracking_history', 'delivery_status')
    # ### end Alembic commands ###
